name: "CodeQL Analysis"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform analysis
      uses: github/codeql-action/analyze@v1
      with:
        # Path to the main CodeQL query file for your analysis
        # Replace the example query path with your own query path.
        query: .github/codeql/myquery.ql

        # Path to the CodeQL database that the analysis should use
        # By default, the database is stored in the workspace directory.
        # If you specify a different path, make sure the directory exists.
        database: ${{ github.workspace }}/codeql-database

        # Path to the CodeQL CLI executable (optional)
        # If not specified, the default CodeQL CLI executable will be used.
        #cli: /path/to/codeql-cli

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to the SARIF file that contains the analysis results
        # This should match the output file specified in your CodeQL query.
        # Replace the example SARIF path with your own SARIF path.
        sarif_file: codeql-results.sarif
